server :
  port : 8080

spring :
  h2:
    console:
      enabled: true # devtool 에서 설정 해주긴 함
      path: /testdb
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=mysql;
    username: sa
    password :
    generate-unique-name: false
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
